name: first_deployment
on:
  push:
    branches:
      - master
  
  status:
    - name: curl
      uses: wei/curl@master
      with:
        args: http://3.110.77.174/opt/deployment.cgi
        CI: true
