name: first_deployment
on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: linux

    strategy:
      matrix:
        Apache: [2.4.51]

    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: http://http://3.110.128.233/opt/deployment.cgi
        CI: true
